### PR TITLE
Fix connection to existing kernel (issue #374)

### PR DESCRIPTION
**Pull request by n-riesco**

### CODE REVIEW

**Comment by lgeiger** [comment]
Thanks for fixing this and noticing the broken async tests! I didn't noticed it because the `getKernelspecs` tests worked fine because they returned the kernelspecs immediately  since `kernelManager._kernelSpecs` was set.

**Comment by n-riesco** [comment]
@lgeiger I think we're ready for a minor release.

In the release notes, I'd warn people that the websocket functionality is still work in progress.

**Comment by n-riesco** [comment]
I've just noticed #394 . I'll push a PR before release.

**Comment by n-riesco** [comment]
@lgeiger Oh! Just merged your PR to fix #394 .

**Comment by lgeiger** [comment]
> @lgeiger Oh! Just merged your PR to fix #394 .

My PR doesn't fix #394 all the way. The shutdown works now but there is still an uncaught error in the dev console because Hydrogen is unable to start the kernel again after shutdown.

**Pull request merged**
