### PR TITLE
Add troubleshooting info for windows paths

### PR DESCRIPTION
**Pull request by andb0t**
This PR is connected to issue #906 and documents how to use kernels from virtual environments on windows.

### CODE REVIEW

**Comment by lgeiger** [comment]
@andb0t Are you interested in helping us maintain Hydrogen? I'd be really happy to add you to the nteract organization. We could really need more Windows experts 😄

**Comment by andb0t** [comment]
Sure, I'd be glad to help where I can. Do you have any special best practices, regulations, minimum contributions per time unit etc, that I should know of?

**Comment by BenRussert** [comment]
In my experience there aren't any strings attached. I think we are just happy to have contributions.

**Comment by andb0t** [comment]
Great, then I'd be happy if you would add me!

**Comment by lgeiger** [comment]
Welcome to nteract 🎉

**Pull request merged**
