### PR TITLE
Add visual indication of modified code (See issue #130)

### PR DESCRIPTION
**Pull request by onyxfish**
Here is a basic implementation of the visual highlights discussed in #130. A few notes:

* I added an opt-in config switch.
* The highlights are now cleared when the kernel is restarted.
* There is a block of Ruby-specific code [here](https://github.com/onyxfish/hydrogen/blob/master/lib/main.coffee#L298) that I couldn't suss out the purpose of. All my test cases seem to work fine with it commented out.
* I haven't been able to get the `contrast` selection for the highlight color to work to my satisfaction. Do you have a better idea how to select a good color?
* There may be a weird case where the selected code errors and you don't display a persistent result bubble, but the highlight persists. I had a hard time tracing the logic of showing/not showing the result "flag" so I wasn't sure where to check if the highlight should persist.

I substantially reimplemented the code to find the correct row range. I think it's quite bit simpler now. Hopefully you agree.

Let me know if you see other issues! I tested against Python and Ruby.

### CODE REVIEW

**Comment by willwhitney** [comment]
Oh! That isn't actually Ruby-specific code. It ensures that if you've selected a bunch of blank lines at the end of your selection, Hydrogen doesn't send the empty lines to the kernel, and puts the results in the appropriate place. This is the behavior we want:



If I do the same thing with your PR, I get this:

screenshot 2015-11-08 12 51 18

> I substantially reimplemented the code to find the correct row range.

Good man! That was some of the first code I wrote on this project, and as a result the messiest. Thanks for this!

> There may be a weird case where the selected code errors and you don't display a persistent result bubble, but the highlight persists. I had a hard time tracing the logic of showing/not showing the result "flag" so I wasn't sure where to check if the highlight should persist.

I'm guessing you mean whether to show the result inline or as a popped-out bubble? The logic for that is in [ResultView](https://github.com/willwhitney/hydrogen/blob/master/lib/result-view.coffee#L73) and the function used to change that is [`setMultiline`](https://github.com/willwhitney/hydrogen/blob/master/lib/result-view.coffee#L146). `setMultiline` just adds/removes a CSS class. ResultView is pretty due for a refactor.

I think the highlight should pretty much always persist, even if the result is an error. It's not really feasible for Hydrogen to know if some code ran to completion, or only the first few lines of it ran, or whatever else. Given that, keeping a consistent rule that "highlighted means I ran it" seems reasonable.

> I haven't been able to get the contrast selection for the highlight color to work to my satisfaction. Do you have a better idea how to select a good color?

I'll play with this a little to see if I can figure something out.

---------

I found a bug in the code that finds the block to run: https://gist.github.com/willwhitney/a537b9b8a12b01806b43

**Comment by willwhitney** [comment]
The color switching seems to work great if we contrast with `@syntax-background-color` instead of `@syntax-text-color`:

screenshot 2015-11-08 13 24 42
screenshot 2015-11-08 13 24 30

Using `contrast` against the text color will pick the color that's further away from the text color; for light text on dark background, that will pick the darker background option. But `contrast` against the background color will lighten a dark background or darken a light one.

Here's the changed line:

```less
.line.hydrogen-run {
    background-color: contrast(@syntax-background-color, @background-color-dark, @background-color-light, 20%);
}
```

**Comment by willwhitney** [comment]
I also just noticed that it's impossible to see whether a line is currently selected or not when this is used. Adding some transparency might work?

**Comment by onyxfish** [comment]
Fixed the highlight/contrast issue and the blank line trimming. Trying to replicate the other traceback you linked to. Spinning up a lua dev environment now.

**Comment by onyxfish** [comment]
So, I'm still setting up my build environment, but I'm noticing that lua folds differently than other languages in atom. I'm wondering if this could be an issue with the lua module:

screen shot 2015-11-09 at 8 27 22 pm

screen shot 2015-11-09 at 8 27 26 pm

**Comment by onyxfish** [comment]
Okay, I see now. The difference in how lua folds means that even though this row triggers the "end" special case, that logic can't find the correct row range because "end" is not considered part of the fold. I believe this code from before the refactor was addressing this case:

```
if @getRow(range[1] + 1).trim() == 'end'
    range[1] = range[1] + 1
```

However, this code, for languages that fold "correctly" could cause one extra line to be executed, if end wasn't followed by whitespace.

Thoughts?

**Comment by willwhitney** [comment]
Ah, yeah. If there are two consecutive `end`s in a language that folds properly, this will run one `end` too many. Initially piggybacking on Atom's folding to find blocks saved a bunch of time, but it definitely has its problems. 

The Right solution probably involves language-specific parsing code, and I'm planning on implementing plugins for Hydrogen that support this whenever I get a solid block of time to work on it.

Until then, do you think indentation level would be a more consistent indicator? Or is there something else we could use as a proxy for this?

**Comment by onyxfish** [comment]
Hey, I can try using indentation--that would be my best guess for something that will work. Although that's only truly reliable for languages with significant whitespace. I didn't realize until I started digging into this that the language folding is implemented in such an approximate manner. The Atom grammars themselves don't define the fold points. (Which is surprising, because the Textmate spec the grammars are based on does.)

I've been wrapped up in starting a new job this week, but I'm starting two weeks of vacation next week so I can take a deeper dive on this then.

**Comment by willwhitney** [comment]
Awesome! Congrats on the new job :)

**Comment by terraqout** [comment]
@onyxfish What is status of this PR?

**Comment by onyxfish** [comment]
It works except for the whitespace issue. Unfortunately I've been totally absorbed in my new job so I haven't had any time to figure out the solution to that problem. If somebody wants to jump in here they should feel free.

**Comment by rgbkrk** [comment]
I'll go ahead and close this. If you pick it up or another person does @onyxfish, let's have at it.

**Pull request closed without merging**
