### PR TITLE
Update Troubleshooting.md

### PR DESCRIPTION
**Pull request by LuizGyro**
Accounting for when "No kernel for grammar Null Grammar found" message is displayed.
This was an issue that came up when I was setting up, one which had a very simple solution,
but I had to look on a separate forum post to find. I think it should be present in the
documentation.

### CODE REVIEW

**Comment by wadethestealth** [comment]
IMO: This doesn't seem like a hydrogen issue. If you have no grammar, then you obviously wont be able to open a kernel which requires a grammar. However the file extension is denoted in grammars, and you can also point any kernel to any grammar in Hydrogen package settings, which means that the 'correct' file extension actually is *not* required.

**Comment by LuizGyro** [comment]
I understand. Maybe it would be better to instead add what you said to the troubleshooting page, then?

**Comment by wadethestealth** [comment]
Could you explain why someone wouldn't use a normal file type that isn't caught by atom grammars, which use hundreds of different file types?
And if they are using a non normal file type why wouldn't they use a grammar for atom to color their keywords correctly??

**Comment by LuizGyro** [comment]
The issue does not reside in either of the situations you described.
It is when a user is eager to test the new package, so they create a new file, but fail to save it before using hydrogen. Then, if they are inexperienced, they might be frustrated, because there is no direct reference to the problem they are having in the Troubleshooting section.
I know it may sound like a stretch, but it can happen.

**Comment by wadethestealth** [comment]
@LuizGyro could you review #1643 and see if this makes sense to you and would be helpful for a beginner?

**Pull request closed without merging**
