### PR TITLE
fix(keymap): Don't override ctrl-backspace

### LINKED ISSUE #555: Don't override ctrl-backspace
Please don't override the `ctrl-backspace` shortcut.

It is a standard shortcut for "delete a word before the cursor". Overriding it confuses those who use it.

### PR DESCRIPTION
**Pull request by lgeiger**
Fixes #555

### CODE REVIEW

**Comment by lgeiger** [comment]
Should we ship a patch release?

**Comment by rgbkrk** [comment]
This does change user land behavior, would it really be major or was it never able to work right before with this prior key binding?

**Comment by lgeiger** [comment]
I'm not sure if it ever worked correctly. To be save and if we want to adhere strictly to semver it would be a major release. But I don't think we're quite ready for `v2.0.0`.

**Comment by rgbkrk** [comment]
I think doing a patch release is A-OK.

**Pull request merged**
