### PR TITLE
Fix: Don't break layout for small line heights

### LINKED ISSUE #228: 0.8.0 output messes up layout
See attached screenshot with Julia kernel. (There are no spaces before the statements; Hydrogen is repositioning the text.)

screen shot 2016-03-27 at 3 14 25 pm

Here's python:

screen shot 2016-03-27 at 3 18 29 pm

### PR DESCRIPTION
**Pull request by lgeiger**
Fixes #228

### CODE REVIEW

**Comment by n-riesco** [comment]
I've set the line height to 1.1 and this PR doesn't fix the issue for me. See below:

untitled

**Comment by lgeiger** [comment]
Weird. Does it work now?

**Comment by n-riesco** [comment]
Yes, it does! If you're happy with the PR, I will merge it.

I've found another issue with the block decorations, but it's better to open a new issue.

**Comment by lgeiger** [comment]
Great!

**Comment by rgbkrk** [comment]
Would you want to ship a patch release or wait until the block decoration fix?

**Comment by n-riesco** [comment]
@rgbkrk I've just submitted a PR to fix the other issue.

**Pull request merged**
