### PR TITLE
Use monospace font in output area

### PR DESCRIPTION
**Pull request by kylebarron**
Fixes https://github.com/nteract/hydrogen/issues/1366.
Fixes https://github.com/nteract/hydrogen/issues/1288.

This submits the fix found by @bigheadming in https://github.com/nteract/hydrogen/issues/1366. He also raised the issue of bad contrast with output colors, but that is a separate issue (https://github.com/nteract/hydrogen/issues/894).

### CODE REVIEW

**Comment by BenRussert** [comment]
Cool, thanks!

**Comment by joolius** [comment]
monospace is ugly. now every time I update hydrogen I have to outcomment that line... can we make it an option?

**Comment by aviatesk** [comment]
If you can accept something bad described in #1366, you can put something like below into your stylesheet:

```less
.hydrogen {
  .output-area .multiline-container {
    font-family: var(--editor-font-family);  // Or the font name you want to use in output pane
  }
}
```

**Comment by joolius** [comment]
Beautiful solution to an ugly problem, thanks!

**Pull request merged**
