### PR TITLE
Fix folding of cells

### LINKED ISSUE #1508: Bug with folding current cell
```py
# %%
print('hello world')
# %%

```
The cell folds incorrectly when the next cell marker is on the following line without an empty line:
image
image

### PR DESCRIPTION
**Pull request by wadethestealth**
Closes #1508

### CODE REVIEW

**Comment by aviatesk** [comment]
@wadethestealth 
Thanks for addressing this issue ! Your fix works.

As a further fix, I wonder you feel like you can fix this too ?
`fold-current-cell` for multiple grammar files (like markdown) can fold multiple cells if invoked on _header of cell_. Please refer to the example below:

Before folding:
image

After folding (dispatch on ` ```python`):
image

**Comment by wadethestealth** [comment]
@aviatesk Currently this is impossible. We currently detect for embedded scopes, which the header is not apart of. The other way to detect would be a markdown code block, but this is specific to markdown and if two code blocks have no blank line between them they will read as the same block. So for now its worth noting that the header is not a part of the cell

**Comment by aviatesk** [comment]
@wadethestealth 
Oh so if I dispatch `fold-current-cell` on an header, the detected scope would be just an grammar of the body text (like markdown, pweave markdown or so) ?

Then I wonder we should disable the command on a body text of multi-grammar files including header.

**Comment by wadethestealth** [comment]
You are totally right since markdown isn't considered a cell but more of a wrapper @aviatesk

**Comment by aviatesk** [comment]
@wadethestealth 
Okay. Anyway, let's put this to another PR/issue.

**Pull request merged**
