### PR TITLE
Try out new IPython completer API

### PR DESCRIPTION
**Pull request by lgeiger**
Implement support for https://github.com/ipython/ipykernel/pull/222
bildschirmfoto 2017-05-30 um 15 04 38

Thanks @Carreau for the great work!

One thing I noticed while testing is that the new completions are noticable slower than before, though speed improves a bit with time once the jedi cache gets populated.

### CODE REVIEW

**Comment by Carreau** [comment]
> One thing I noticed while testing is that the new completions are noticable slower than before, though speed improves a bit with time once the jedi cache gets populated.

Yes, we had a couple of complaint about that. I need to find some time to work on jedi.

**Comment by rgbkrk** [comment]
Does it also bust the cache if you upgrade a package?

**Comment by Carreau** [comment]
I believe the cache is based on the hash of the files content. I'm unsure if it deletes the cache, but at least it won't give outdated result.

**Comment by rgbkrk** [comment]
IPython master now has this and we've merged it for nteract desktop to start iterating on. What do you think about bringing this in @lgeiger?

**Comment by Carreau** [comment]
> IPython master

Technically IPython stable and IPykernel master.

**Comment by lgeiger** [comment]
> IPython master now has this and we've merged it for nteract desktop to start iterating on. What do you think about bringing this in @lgeiger?

Should be good to bring in 🚀

**Pull request merged**
