### PR TITLE
Add a snippet to use the data explorer

### PR DESCRIPTION
**Pull request by BenRussert**

### CODE REVIEW

**Comment by BenRussert** [comment]
I was going to add this as a separate gitbook file, but either I can't remember how to add a page or something isn't working right. Could only edit existing pages.

Anyway, figure we should add this and ship!

**Comment by BenRussert** [comment]
Well look at that, the build is broken. Was working fine with stale local packages, but if I fresh `apm install` I get:

```
Cannot find module 'atom-jasmine3-test-runner' from '/home/path/to/hydrogen/'
Error: Cannot find module 'atom-jasmine3-test-runner' from '/home/path/to/hydrogen/'
    at Function.module.exports [as sync] (/usr/share/atom/resources/app.asar/node_modules/resolve/lib/sync.js:42:15)
    at AtomApplication.resolveTestRunnerPath (/usr/share/atom/resources/app.asar/src/main-process/atom-application.js:1234:37)
    at AtomApplication.runTests (/usr/share/atom/resources/app.asar/src/main-process/atom-application.js:1151:33)
    at AtomApplication.openWithOptions (/usr/share/atom/resources/app.asar/src/main-process/atom-application.js:231:19)
    at optionsForWindowsToOpen.map.options (/usr/share/atom/resources/app.asar/src/main-process/atom-application.js:204:56)
    at Array.map (<anonymous>)
    at AtomApplication.launch (/usr/share/atom/resources/app.asar/src/main-process/atom-application.js:204:36)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by BenRussert** [comment]
Thanks @rgbkrk for the fix! I'm thinking I'll ship tonight.

**Comment by rgbkrk** [comment]
Docs are awesome! ❤️📑

**Comment by rgbkrk** [comment]
Great! Did you also pick up the latest changes to the data explorer? When I shipped all the packages I did push out a new transform dataresource.

**Comment by BenRussert** [comment]
I'll give it a full fresh install and try it out before shipping

**Pull request merged**
