### PR TITLE
Remove requirejs dependency

### LINKED ISSUE #793: Uncaught Error: Tried loading "pdfjs-dist/build/pdf.worker" at /Applications/Atom.app/Contents/Re...
[Enter steps to reproduce:]

1. launch hydrogen
2. open pdf

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package 1.13.0

### Stack Trace

Uncaught Error: Tried loading "pdfjs-dist/build/pdf.worker" at /Applications/Atom.app/Contents/Resources/app/static/pdfjs-dist/build/pdf.worker.js then tried node's require("pdfjs-dist/build/pdf.worker") and it failed with error: Error: Cannot find module 'pdfjs-dist/build/pdf.worker'

```
At /Users/me/.atom/packages/Hydrogen/node_modules/requirejs/bin/r.js:2607

Error: Tried loading "pdfjs-dist/build/pdf.worker" at /Applications/Atom.app/Contents/Resources/app/static/pdfjs-dist/build/pdf.worker.js then tried node's require("pdfjs-dist/build/pdf.worker") and it failed with error: Error: Cannot find module 'pdfjs-dist/build/pdf.worker'
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:2600:27
    at Object.execCb (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1946:33)
    at Object.check (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1133:51)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1426:22)
    at Object.init (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1038:26)
    at callGetModule (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1453:63)
    at Object.completeLoad (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1840:21)
    at Function.req.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:2613:17)
    at Object.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1935:21)
    at Object.load (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1084:29)
    at Object.fetch (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1074:66)
    at Object.check (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1106:30)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1426:22)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1807:39)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:1411:33)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:384:23
    at each (/packages/Hydrogen/node_modules/requirejs/bin/r.js:309:31)
    at Object.enable (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1363:17)
    at Object.init (/packages/Hydrogen/node_modules/requirejs/bin/r.js:1038:26)
    at /packages/Hydrogen/node_modules/requirejs/bin/r.js:1710:36
```

### Commands

```
     -0:54.6.0 core:save (input.hidden-input)
     -0:51.3.0 core:backspace (input.hidden-input)
     -0:50.5.0 core:save (input.hidden-input)
  3x -0:47.2.0 editor:newline (input.hidden-input)
     -0:39.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
ask-stack 2.2.0 
atom-beautify 0.29.24 
atom-python-run 0.7.3 
auto-encoding 0.7.0 
auto-update-packages 1.0.1 
autocomplete-python 1.8.63 
autocomplete-R 0.6.0 
browser-plus 0.0.87 
build 0.67.0 
build-rscript 0.6.1 
busy 0.7.0 
busy-signal 1.4.1 
data-atom 0.25.1 
Ensime 0.41.0 
gist 0.4.0 
git-projects 1.17.0 
Hydrogen 1.13.0 
hyperclick 0.0.40 
intentions 1.1.2 
keybinding-cheatsheet 0.1.1 
kite 0.23.0 
language-latex 1.0.0 
language-markdown 0.22.0 
language-pgsql 0.2.3 
language-r 0.4.1 
language-scala 1.1.8 
language-sql-mysql 0.3.1 
latex 0.43.0 
latex-autocomplete 1.0.0 
latextools 0.8.5 
linter 2.1.4 
linter-ui-default 1.2.4 
markdown-preview-plus 2.4.9 
open-recent 5.0.0 
pdf-view 0.58.0 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
python-debugger 0.2.0 
python-indent 1.0.2 
python-tools 0.6.9 
qolor 0.4.1 
quick-query 0.9.2 
r-exec 0.5.0 
sbt 0.11.0 
scala-format 0.1.8 
sync-settings 0.8.1 
tasks 2.6.6 
todo-show 1.11.0 
```

### PR DESCRIPTION
**Pull request by lgeiger**
While checking out #908 I realized we don't need `requirejs` at all. I tested it and it works fine without.

@nikitakit Was there a specific reason for `requirejs` to be globally available? If not I guess this fixes #793

### CODE REVIEW

**Comment by rgbkrk** [comment]
I think this is so libraries that try to use requirejs end up using this instead of producing a JS error (since the classic notebook uses it).

**Comment by nikitakit** [comment]
The entire shim here is based on the documentation for `@jupyterlab/services`: ideally there would be a way to not install/override any globals, but I did what the docs said was needed just to be safe.

In particular if you look [here](https://github.com/jupyterlab/services#supported-runtimes) you'll see that `requirejs` is needed for Comm targets. So not currently something that hydrogen uses, though I would like to have comm/widgets support in hydrogen eventually.

I guess hydrogen could try removing it, though it would be our responsibility if anything breaks as a result. As far as I can tell the `@jupyterlab/services` maintainers do most of their testing with browser-based code, so the moment we do anything different from the nodejs examples they provide we become responsible for testing all the edge cases that could arise from using the library inside node.

**Comment by nikitakit** [comment]
Just saw https://github.com/nteract/hydrogen/pull/908#issuecomment-332019684: based on this I think it may be possible to do away with the globals shim entirely.

**Comment by lgeiger** [comment]
@nikitakit Thanks for the explanation!

Since `requirejs` is over a MB big and potentially caused #793 I think we could give it a shot and remove it. It's aIso missing in the [minimal node example](https://github.com/jupyterlab/jupyterlab/blob/master/packages/services/examples/node/index.js) from jupyterlab. If we're hitting strange bugs, we can always roll back. What do you think?

> Just saw #908 (comment): based on this I think it may be possible to do away with the globals shim entirely.

I have a rough version of this mostly working, though I'm hitting some bugs on jupyters side. I'll try to submit a PR soon.

**Comment by nikitakit** [comment]
@lgeiger I see, since there are actual problems then it makes sense to try removing it. Unfortunately I'm not sure I'll be able to help with testing this.

**Comment by rgbkrk** [comment]
Should we go ahead and bring this in?

**Comment by lgeiger** [comment]
> Should we go ahead and bring this in?

👍

**Pull request merged**
