### PR TITLE
[WIP] conform to context interface of <MathJax.Context>

### PR DESCRIPTION
**Pull request by rgbkrk**
This is just like the soon-to-be-released `@nteract/markdown`'s `<MathJax.Context>` except it loads using `mathjax-electron`. I'm prepping this PR for handling when I make the release of the packages from the nteract monorepo.

All of a sudden, we're going to have super improved LaTeX handling likely closing quite a few issues. 🎉 

----

~In hindsight I should make this part of the monorepo too, as nteract desktop could also use this.~ Done.

TODO:

* [ ] Make `mathjax-electron`, `@nteract/mathjax` dependencies for Hydrogen
* [ ] Switch to `@nteract/mathjax` for setting up a `<MathJax.Context>` root element above any elements that use display area or transforms.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Tips I need -- what top level element(s) should I register this mathjax context on? It basically needs to be above any element that would render outputs (Markdown or LaTeX).

**Comment by rgbkrk** [comment]
This will need to be upgraded in tandem with #1213, #1214 and use the new way I allowed `<MathJax.Context />` to override how it "loads" MathJax in https://github.com/nteract/nteract/pull/2480

```js
import { loadMathJax } from "mathjax-electron"

...

<MathJax.Context
  loader={(onLoad) => loadMathJax(document, onLoad)}
>
  {someHydrogenElementThatUsesDisplay}
</MathJax>
```

**Comment by lgeiger** [comment]
Woa I ignored this way too long, sorry Kyle. I'll take a look later today.

**Comment by lgeiger** [comment]
> Tips I need -- what top level element(s) should I register this mathjax context on? It basically needs to be above any element that would render outputs (Markdown or LaTeX).

Right now we're registering mathjax globally on the page. This seams to have worked in the past.
`mathjax-electron` was handling this for us: https://github.com/nteract/mathjax-electron/blob/master/index.js#L31

**Comment by rgbkrk** [comment]
That's fine. The MathJax context component can use a global version of MathJax that's already loaded -- all it does it make MathJax available on the context api to other components.

**Pull request closed without merging**
