### PR TITLE
Improve error message if no Python kernels are found

### PR DESCRIPTION
**Pull request by lgeiger**
Make it easier for people to upgrade from the old kernel spec setup:
bildschirmfoto 2017-10-11 um 18 38 03

### CODE REVIEW

**Comment by rgbkrk** [comment]
:shipit:

**Comment by Eric2333** [comment]
I just upgraded my hydrogen from 1.19.something to 2.0.1. After I restart my Atom, and when I try to run some code with cmd + enter. I didn't see the error message above and nothing is responding. I tried those two commands. But everything is still the same - no response. Any clue?

**Comment by BenRussert** [comment]
Do you have the file saved?

**Comment by Eric2333** [comment]
I see. Thank you! @BenRussert

**Comment by BenRussert** [comment]
@Eric2333 no problem, we have an open issue to make that more clear

**Pull request merged**
