### PR TITLE
New demo image

### PR DESCRIPTION
**Pull request by rgbkrk**
hydrogen demo

Created a new one to show off the new styling. Props everyone!

### CODE REVIEW

**Comment by n-riesco** [comment]
It looks so cool!

**Comment by n-riesco** [comment]
I've just noticed the demo is not showing up in https://atom.io/packages/Hydrogen

**Comment by lgeiger** [comment]
I think that's because `0.8.0` was released before the readme update. It should update with the next release.

**Comment by rgbkrk** [comment]
That or we make a patch release.

**Comment by lgeiger** [comment]
@rgbkrk What did you use to make this gif? My gifs always look ugly.

**Comment by rgbkrk** [comment]
On OS X I use [LICEcap](http://www.cockos.com/licecap/).

**Comment by lgeiger** [comment]
Thanks I'll try it immediately.

**Pull request merged**
