### PR TITLE
execute whole file with one command

### PR DESCRIPTION
**Pull request by lgeiger**
As mentioned in issue https://github.com/nteract/hydrogen/issues/74.

Mac: `cmd-ctrl-enter`
Windows: `ctrl-shift-alt-enter`

The result bubble will appear on the last line.

The Mac shortcut is very nice. But I'm not shure if the Windows shortcut is convenient.
Do you have a better idea?

### CODE REVIEW

**Comment by rgbkrk** [comment]
We can go with this for now and a Windows developer can chime in with a tighter binding after with a follow on PR.

**Comment by rgbkrk** [comment]
Welcome to the party! Would you be interested in helping maintain Hydrogen? We're on a relatively new path now that Hydrogen has moved over to nteract, which follows the [C4.1 process](http://rfc.zeromq.org/spec:22). We're lightly planning out future plans in #158, to rely on some common amongst projects node packages.

**Comment by lgeiger** [comment]
This is great. I'm excited to see Hydrogen evolve.

But I'm lacking the knowledge in JavaScript or CoffeeScript to help you maintain Hydrogen. If there are some easy thing I can fix, I'll make a PR.

**Comment by rgbkrk** [comment]
We're all learning through life and happy to help you. Happy to recommend books and tutorials (*ahem* JavaScript the Good Parts).

**Pull request merged**
