### PR TITLE
Fix move down

### LINKED ISSUE #1229: Hydrogen: Run running everything after function definition
**Description:**

Calling Hydrogen: Run or Hydrogen: Run And Move Down when the cursor is on a def line runs the entire document. E.g., below code would immediately output "bye again" "hi again" when you start at either def a(): or def b():.

This happens whether it's called via hotkey or from command palette

example code:
```Python
def a():
    print("hi")

def b():
    print("bye")

print("bye again")
print("hi again")
```
**Steps to Reproduce:**

1. put cursor on either def line in example code
2. call Hydrogen: Run or Hydrogen: Run And Move Down

**Versions:**

Atom    : 1.24.0
Electron: 1.6.16
Chrome  : 56.0.2924.87
Node    : 7.4.0
OS: Windows 10
Hydrogen: 2.2.2

**Logs:**
[-1518819562665.log](https://github.com/nteract/hydrogen/files/1733012/-1518819562665.log)

### PR DESCRIPTION
**Pull request by lgeiger**
Fixes #1229

Looks like Atom changed the behavior here in Atom 1.24.

### CODE REVIEW

**Comment by sunt05** [comment]
When will this patch be applied? Desperately waiting for the update...

**Comment by krystalzeng** [comment]
@sunt05 You can manually overwrite the utils.js file if it's urgent for you. I updated mine according to @lgeiger's fix, and it works for me now.

**Comment by rgbkrk** [comment]
Thanks!

**Comment by sunt05** [comment]
Thanks for the quick response! @rgbkrk

**Comment by lgeiger** [comment]
We published `v2.2.3` including this fix.

**Pull request merged**
