### PR TITLE
Discrete switch for watchs history

### PR DESCRIPTION
**Pull request by lgeiger**
historyswitch
See https://github.com/nteract/hydrogen/pull/143 and https://github.com/nteract/hydrogen/pull/175
It's more intuitive than the scrollbar.

I think it looks a bit cluttered. But I couldn't come up with a better layout.

### CODE REVIEW

**Comment by slavaGanzin** [comment]
I think it would be great to have a scrollbar behind counter too: it would be hard to rewind 1000 history entries by clicking.

Cluttered? Yes, But it looks better than it was. Thanks for your work

**Comment by lgeiger** [comment]
Thanks for the feedback.

I thought about that too.
The problem with the scrollbar for me is that it won't appear on Mac OS because by default scrollbars are hidden on Mac OS. And I don't know how to force show them.

Would an additional skip to start/end button do the trick?

**Comment by slavaGanzin** [comment]
> Would an additional skip to start/end button do the trick?

No. If I have thousands result items.

> default scrollbars are hidden on Mac OS.

And previous scrollbar too?

**Comment by lgeiger** [comment]
OK, I understand. So something like alt-clicking on the button for skipping 10 results at a time wouldn't work to.

I try adding the scrollbar behind the counter.

> And previous scrollbar too?

Yes.

**Comment by slavaGanzin** [comment]
> default scrollbars are hidden on Mac OS.

did you try to change your atom theme?
I think it should be ```.darwin``` specific css rule.

**Comment by lgeiger** [comment]
I added the scrollbar again.
bildschirmfoto 2016-03-01 um 18 40 59

**Comment by rgbkrk** [comment]
Very slick.

**Comment by slavaGanzin** [comment]
Let scrollbar be as tall as history controll.

**Comment by lgeiger** [comment]
I made the scrollbar bigger:
bildschirmfoto 2016-03-03 um 10 43 09

On Mac the scrollbar is shown, depending on your systemwide settings. If not it doesn't break the layout:
bildschirmfoto 2016-03-03 um 10 42 39

**Comment by slavaGanzin** [comment]
Great! I'll test now

**Comment by lgeiger** [comment]
Nice! I hope it works on Windows and Linux as well.

**Comment by slavaGanzin** [comment]
It works! Let's merge
@lgeiger Is there any way to make scrollbar responsive when mousedown triggered on ```div.counter```?

**Comment by lgeiger** [comment]
@slavaGanzin Stackoverflow to the rescue. Just one line CSS ;)
I didn't know this is possible.

**Comment by slavaGanzin** [comment]
@lgeiger Looks like I forget how to use google, I asked after lurking at stackoverflow.

**Comment by rgbkrk** [comment]
:tada: feel free to make a release, you have the power

**Comment by slavaGanzin** [comment]
@rgbkrk I dont know how :)

**Comment by rgbkrk** [comment]
After pulling master / syncing up with master, and making sure that your remote is configured for this source repo:

apm publish minor

Depending on the changes, you can also do major or patch (like npm, with less steps).

**Comment by slavaGanzin** [comment]
@rgbkrk Thanks for clarification

**Comment by rgbkrk** [comment]
Let me know if you want me to publish, I'm happy to as well.

**Comment by rgbkrk** [comment]
Though it looks like there's a new related PR from @lgeiger, so we can hold off til you want to cut the release.

**Pull request merged**
