### PR TITLE
Kernel: Fix bug on ZMQ monitoring disabled

### LINKED ISSUE #248: Uncaught Error: Monitoring support disabled check zmq version is > 3.2.1 and recompile this addon
[Enter steps to reproduce below:]

1. installed Anaconda and jupyter
2. installed libzmq-dev
3. installed hydrogen in atom
4. started atom from terminal
5. created new python file
6.Selected Hydrogen Run
7.Received Hydrogen Kernels Updated: Python 2
8.Received next error:

**Atom Version**: 1.6.1
**System**: Linux Mint
**Thrown From**: [Hydrogen](https://github.com/nteract/hydrogen) package, v0.8.2

### Stack Trace

Uncaught Error: Monitoring support disabled check zmq version is > 3.2.1 and recompile this addon

```
At /home/sf/.atom/packages/Hydrogen/node_modules/jmp/node_modules/zmq/lib/index.js:449

Error: Monitoring support disabled check zmq version is > 3.2.1 and recompile this addon
    at Socket.monitor (/home/sf/.atom/packages/Hydrogen/node_modules/jmp/node_modules/zmq/lib/index.js:449:11)
    at Kernel.module.exports.Kernel.connect (/home/sf/.atom/packages/Hydrogen/lib/kernel.coffee:114:22)
    at new Kernel (/home/sf/.atom/packages/Hydrogen/lib/kernel.coffee:32:10)
    at /home/sf/.atom/packages/Hydrogen/lib/kernel-manager.coffee:105:26
    at /home/sf/.atom/packages/Hydrogen/lib/config-manager.coffee:23:13
    at Object.module.exports.portfinder.findManyHelper (/home/sf/.atom/packages/Hydrogen/lib/find-port.coffee:21:13)
    at /home/sf/.atom/packages/Hydrogen/lib/find-port.coffee:26:18
    at Server.<anonymous> (/home/sf/.atom/packages/Hydrogen/lib/find-port.coffee:14:21)
    at Server.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at Server.emit (events.js:166:7)
    at emitCloseNT (net.js:1518:8)
    at doNTCallback1 (node.js:430:9)
    at process._tickCallback (node.js:352:17)
```

### Commands

```
     -0:01.3.0 hydrogen:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-light-ui",
      "redmond-syntax"
    ]
  },
  "Hydrogen": {
    "kernelspec": "{\"kernelspecs\":{\"python2\":{\"resource_dir\":\"/home/sf/anaconda2/lib/python2.7/site-packages/ipykernel/resources\",\"spec\":{\"language\":\"python\",\"display_name\":\"Python 2\",\"env\":{},\"argv\":[\"/home/sf/anaconda2/bin/python\",\"-m\",\"ipykernel\",\"-f\",\"{connection_file}\"]}}}}"
  }
}
```

### Installed Packages

```coffee
# User
Hydrogen, v0.8.2
ascii-hex, v0.2.0
build, v0.55.0
hex, v0.6.2
indent-guide-improved, v1.4.5
java-class-complete, v0.0.2
java-importer, v1.4.1
language-java, v0.17.0
linter, v1.11.3
linter-flake8, v1.12.0
linter-javac, v1.8.0
minimap, v4.19.0
python-tools, v0.6.7
redmond-syntax, v0.2.16
tabs-to-spaces, v1.0.2

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by n-riesco**
Fixes #248

### CODE REVIEW

**Comment by lgeiger** [comment]
Works for me :+1:

**Comment by rgbkrk** [comment]
That'll work!

**Comment by rgbkrk** [comment]
We have enough piled up here that I'll go ahead and make a patch release since it's this bug fix + style changes.

**Comment by rgbkrk** [comment]
```
$ apm publish patch
Preparing and tagging a new version ✓
Pushing v0.8.3 tag ✓
Publishing Hydrogen@v0.8.3 ✓
```

**Pull request merged**
