### PR TITLE
KernelManager: Use lower-case language names

### LINKED ISSUE #222: Trouble with Elixir
I'm trying to use Hydrogen with Elixir (using the https://github.com/pprzetacznik/IElixir) but I'm having some trouble. I've installed IElixir like so:

```bash
$ git clone https://github.com/pprzetacznik/IElixir.git
$ cd IElixir
$ mix deps.get
$ MIX_ENV=prod mix compile
$ sh install_script.sh
```

And when I run Hydrogen on an Elixir file, I get the following error:

### Stack Trace

Uncaught No such kernel!

```
At /Users/aop/.atom/packages/hydrogen/lib/kernel-manager.coffee:161

undefined
```

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [hydrogen](https://github.com/willwhitney/hydrogen) package, vundefined

One strange thing is that the  Hydrogen version is showing as undefined, but I can still use Hydrogen with other languages (e.g., Babel/Javascript). 

Any idea what I might be doing wrong?

### PR DESCRIPTION
**Pull request by n-riesco**
Fixes #222

### CODE REVIEW

**Comment by n-riesco** [comment]
@slavaGanzin @lgeiger @rgbkrk Since this PR fixes a bug, I think we should make a new patch release after merging.

**Comment by lgeiger** [comment]
Great! :+1:

**Comment by rgbkrk** [comment]
With all the other changes that went in [since v0.7.2](https://github.com/nteract/hydrogen/compare/v0.7.2...master), I say we make a minor release `v0.8.0`.

**Comment by rgbkrk** [comment]
Also, :+1: to the lowercasing for normalization.

**Comment by rgbkrk** [comment]
```
$ apm publish minor
Preparing and tagging a new version ✓
Pushing v0.8.0 tag ✓
Publishing Hydrogen@v0.8.0 ✓
```

**Comment by rgbkrk** [comment]
Done deal.

**Comment by n-riesco** [comment]
Wow! I blink and all is over! :tada:

**Comment by rgbkrk** [comment]
We had so much sitting here that it was scaring me a little bit. Since we needed this one to go out, aimed for a minor release. Time to see how people like it. It's a LOT of fun to use right now.

**Comment by rgbkrk** [comment]
On a side note, it would be great if folks added on to the release notes. I added a few things, definitely didn't capture all (since there was a good bit of refactoring work).

**Comment by n-riesco** [comment]
Not today, but at some point we should discuss the list of things we would like to have for v1.0.0.

**Comment by rgbkrk** [comment]
I'd love if we somehow finish off the zmq prebuilt story so we have less bug reports related to installation/python2/node-gyp/needing headers.

**Pull request merged**
