### PR TITLE
Allow run command to activate hydrogen

### PR DESCRIPTION
**Pull request by lgeiger**
Forgot to add these commands in https://github.com/nteract/hydrogen/pull/164 and https://github.com/nteract/hydrogen/pull/165

### CODE REVIEW

**Comment by rgbkrk** [comment]
That missing comma! :eyes:

**Comment by rgbkrk** [comment]
@lgeiger would you like to help us maintain this package, aiming for #158? We love accepting your patches and hope you'll love ours too. :wink:

**Comment by lgeiger** [comment]
@rgbkrk I would like to help you maintain this package.
However, these PRs are the first lines of Coffeescript/Javascript I've written so far. But I hope I can contribute some tweaks here and there ;)

**Comment by rgbkrk** [comment]
Welcome to the nteract party! :tada:

We're all learners. :smile:

**Pull request merged**
