### PR TITLE
Fix history css slider issues

### PR DESCRIPTION
**Pull request by xanecs**
Ref #1030

### CODE REVIEW

**Comment by lgeiger** [comment]
Looks excellent 👍 
bildschirmfoto 2017-10-17 um 00 07 45

**Comment by lgeiger** [comment]
Congrats to your first PR on Hydrogen 🎉 

Are you interested in helping us maintain Hydrogen? I'd be happy to add you to the nteract organization.

**Comment by xanecs** [comment]
Of course,
Im just gettings started with atom packages but I'll see what I can do.

**Comment by lgeiger** [comment]
🆒 Welcome to nteract.

**Comment by BenRussert** [comment]
Awesome! :shipit:

**Pull request merged**
