### PR TITLE
Add support for language-weave latex and reStructuredText

### PR DESCRIPTION
**Pull request by mpastell**
This adds support for running code from Latex and reStructuredText flavored documents with `language-weave`

### CODE REVIEW

**Comment by mpastell** [comment]
I've added the links. This is really a great feature that makes working with literate documents much easier!

**Comment by mpastell** [comment]
I'll keep that in mind. Pweave doesn't currently support multiple kernels, but that would be interesting to add in the future. I'm adding a section to Pweave docs about using `language-weave` with Hydrogen.

**Comment by BenRussert** [comment]
@mpastell yep, I just meant rich documents documents in general. 

> I'm adding a section to Pweave docs about using language-weave with Hydrogen

Sounds cool, I hope you post a link here when you are done, or I can just look out for it 😄

**Comment by mpastell** [comment]
New docs are now online: http://mpastell.com/pweave/editors.html

**Pull request merged**
