### PR TITLE
Close issue #1963 (tooltip not shown)

### PR DESCRIPTION
**Pull request by PhilippImhof**
This closes issue #1963 by giving the display div for inline results a bit more height.

### CODE REVIEW

**Comment by aviatesk** [comment]
imho this looks really ugly, no ?
image

**Comment by PhilippImhof** [comment]
I agree that it is not the most beautiful solution, however, I would not call that _really ugly_. Do you have a better idea? (Making it larger did not work for me.) A solution could be to add a small clipboard icon to the right, like you do for multi-line output.

Maybe it would look better, if the content was vertically centered. Further testing showed me that `min-height: 1.8em` would be enough; smaller sizes would not work anymore.

If I have the choice between a very beautiful inline result that cannot be copied and a copyable that is a bit less beautiful, I would definitely choose the latter. I would even prefer a _real ugly_ solution that works to a beautiful one that doesn't.

**Comment by aviatesk** [comment]
The problem is that I can't reproduce your problem and we've not received issues like yours.
So my hunch is that your have some weird stylesheet setup or your theme does that.
I suggest you can keep this change in your `~/.atom/stylesheet.less`, and imho this change is not worth to be upstreamed (i.e. in this repository).

**Comment by PhilippImhof** [comment]
OK,  thanks. I have no custom stylesheet setup and I tried atom-dark and atom-light themes, so both pretty standard. It might be OS specific, though. But if you do not want to or see no need to fix it, I will just change my local stylesheet.

**Comment by aviatesk** [comment]
> I have no custom stylesheet setup and I tried atom-dark and atom-light themes, so both pretty standard. It might be OS specific, though.

ah, really ? Which OS, if you wouldn't mind ? 
I agree with that we don't have such a good stylesheet that looks all fine on all the environment (I personally have some hydrogen-specific setups in my stylesheet as well), but imho forcing the look above for every user would be a very big deal.

**Comment by PhilippImhof** [comment]
Ah sorry, I thought you saw that on the bug report. I'm on macOS 10.14.6. 

I see your point that having the output look worse might not be acceptable to users who do not have the problem. I will try a solution with a small clipboard icon on the right side, keeping the regular height.

**Pull request closed without merging**
