### PR TITLE
Make text in panes (inspector, output, watch) copyable

### PR DESCRIPTION
**Pull request by ttor**
added `native-key-binding` class and `tabindex:-1` to panes to allow copying via ctrl-c from them
addresses #989 and #845 (related: #954)
inspired by rgbkrk/atom-script/pull/79

### CODE REVIEW

**Comment by lgeiger** [comment]
@ttor Do you want to help us maintain Hydrogen? We'd be very happy to add you to the nteract organization.

**Comment by BenRussert** [comment]
Oh, nice! Thanks @ttor!

**Comment by ttor** [comment]
@lgeiger I'd love to help out with Hydrogen. Let me first try to get a little more comfortable with the codebase and maybe solve a few issues.

**Comment by lgeiger** [comment]
@ttor That's awesome! Welcome to nteract 🎉

**Pull request merged**
