### PR TITLE
Kernel fixes

### LINKED ISSUE #374: `hydrogen/connection.json` broken in MASTER
Moved from https://github.com/nteract/hydrogen/issues/367#issuecomment-233668341

We should fix this before next release.

### PR DESCRIPTION
**Pull request by n-riesco**
I wanted to fix #374 but I didn't get that far.

This PR:
- removes `ConfigManager`
- refactors some of the code in `KernelManager` and `ZMQKernel` to help address #374 
- fixes a leak of connection files
- and a necessary fat arrow

### CODE REVIEW

**Comment by n-riesco** [comment]
@lgeiger I've just had a look at your PR #386 and noticed we're touching the same code (and doing similar things).

Which PR do you think we should merge first?

**Comment by n-riesco** [comment]
Oops! Forgot to run the specs! :blush:

**Comment by lgeiger** [comment]
> @lgeiger I've just had a look at your PR #386 and noticed we're touching the same code (and doing similar things).
Which PR do you think we should merge first?

I had a quick look at your changes and think the rebase is easier if #386 gets merged first:
- [`f4d02ca`](https://github.com/nteract/hydrogen/pull/389/commits/f4d02ca17c29858c33da49b7b97fb27285ccbd80) can be removed  since the connectionfile will be handled by `spawnteract`
- the other commits shouldn't be that hard to rebase.

**Comment by n-riesco** [comment]
@lgeiger Have a look at https://github.com/nteract/hydrogen/pull/389/commits/dd0b9a151786fb39adccf8ed34ebe1d9b03f511f . I noticed the `done()` pattern wasn't working in our asynchronous tests. This is due to Atom using Jasmine v1.3. I've updated the asynchronous tests to use `waitsForPromise` (a helper provided by Atom).

**Pull request closed without merging**
