### PR TITLE
Use block decorations to show output results

### LINKED ISSUE #48: overlap problem
Sorry about my poor English. I'm trying to report this by screenshot.
It happens when the codes are long enough and you scroll down.
qq 20150529195641

### LINKED ISSUE #205: Pandas dataframes cut off
Attempting to display a pandas dataframe returns a HTML representation (great!), however, scrolling around the dataframe does not seem to work: the display clips.
dataframe_issue

### PR DESCRIPTION
**Pull request by n-riesco**
* Requires Atom v1.6.0+

Fixes #205
Fixes #48

### CODE REVIEW

**Comment by n-riesco** [comment]
@lgeiger 


* Sorry about breaking the ANSI colours (I should've remembered you just implemented that). Could you open a separate issue for it?

* SVG works for me, Could you show me how to reproduce the failure you see?

* Could you open a separate issue for the error notifications?

* I will address the issue with the font size in this PR

**Comment by lgeiger** [comment]
Awesome!

This isn't working for me in Atom 1.6.0
```
%matplotlib inline
%config InlineBackend.figure_format = 'svg'
import matplotlib.pyplot as plt
import numpy as np

t = np.arange(0.0, 2.0, 0.01)
s = np.sin(2 * np.pi*  t)

plt.plot(t, s)
plt.show()
```

**Comment by n-riesco** [comment]
@lgeiger For the issue with SVG, could you try to check the logs as described in #204 ?

**Comment by lgeiger** [comment]
Hmm I can't find an IO message with `prefix` `"display_data"`:
bildschirmfoto 2016-03-18 um 20 25 02

**Comment by lgeiger** [comment]
Side note:
Do you think we can move the checkmarks inline despite being block decorations?

**Comment by n-riesco** [comment]
@lgeiger Thanks for the code. Now I can reproduce it.

**Comment by n-riesco** [comment]
@lgeiger, re checkmarks: I don't think so. The block decorations don't even live in the same `div` as the code line.

**Comment by n-riesco** [comment]
@lgeiger The problem with SVGs is triggered with SVG that do not start with an <svg> tag. In your example, if I remove the first few line, Hydrogen shows the image:

```svg
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Created with matplotlib (http://matplotlib.org/) -->
<svg height="255pt" version="1.1" viewBox="0 0 378 255" width="378pt" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
...
</svg>
```

**Comment by n-riesco** [comment]
@lgeiger Is this font size ok?

untitled

**Comment by lgeiger** [comment]
looks good to me :+1:

**Comment by rgbkrk** [comment]
Woo, awesome!!!

**Comment by n-riesco** [comment]
@rgbkrk The problem displaying SVGs was caused by `transformime-jupyter-transformers`. The SVG transformer converts the SVG data into a DOM element [here](https://github.com/nteract/transformime-jupyter-transformers/blob/140291e2440bf33a125a6345e3e73e857420ae43/src/svg.transform.js#L7-L8) but it only returns [the first child](https://github.com/nteract/transformime-jupyter-transformers/blob/140291e2440bf33a125a6345e3e73e857420ae43/src/svg.transform.js#L9), which often is just a comment.

I see two ways to fix this:
* as I have done [in Hydrogen](https://github.com/n-riesco/hydrogen/blob/block-decorations/lib/result-view.coffee#L213-L218)
* or alternatively, return the `<div>` element with all the child nodes (but this isn't friendly with styles).

**Comment by rgbkrk** [comment]
Yuck, thanks for finding the problem @n-riesco. Seems like with your solution, transformime for jupyter should behave just like the rest of the image transforms.

**Comment by rgbkrk** [comment]
Related project to dig through (not necessarily rely on), for Jupyter output in general: https://github.com/nteract/jupyter-display-area

**Comment by rgbkrk** [comment]
Seems like we're definitely gearing up for a major release here.

**Comment by slavaGanzin** [comment]
Hello everyone, I accidentally make git pull because wanted to fix #205. And now I have no result bubbles at all. Should I recompile anything or ...?

And if we decided to move to block decorations, I think we shouldn't use different font(which was great in visual separating hydrogen popups from code) and use user defined.

**Comment by n-riesco** [comment]
On 19/03/16 12:52, Slava wrote:
> Hello everyone, I accidentally make git pull because wanted to fix #205 <https://github.com/nteract/hydrogen/issues/205>. And now I have no result bubbles at all. Should I recompile anything or ...?

There are new dependencies. Try `apm install` on the Hydrogen folder.

> And if we decided to move to block decorations,

I'm OK with trying other solutions, but we do need to move away from overlays because they're meant for auto-completion lists.

> I think we shouldn't use different font(which was great in visual separating hydrogen popups from code) and use user defined.

Transformime wraps 'text/plain' with a `<pre>` tag. If you want to play with the style, have a look at these lines:

https://github.com/nteract/hydrogen/blob/104d8cee62b53c78e01d4b37b80b208be936abc6/styles/hydrogen.less#L109-L117

and

https://github.com/nteract/hydrogen/blob/104d8cee62b53c78e01d4b37b80b208be936abc6/styles/hydrogen.less#L133-L141

**Comment by slavaGanzin** [comment]
I cloned hydrogen, make apm install and nope it doesn't work for me even with default atom styling. Result blocks aren't visible.

> Transformime wraps 'text/plain' with a `<pre>` tag. If you want to play with the style, have a look at these lines:

I think it would be better do not use <pre> in transformime and just use span with:
```
.preformatted {
    white-space: pre;
}
```
Should I describe why?

**Comment by rgbkrk** [comment]
Make the PR and explain there. I did the same with spans inside a code block in nteract/nteract, when using ansi-to-react.

**Comment by n-riesco** [comment]
What Atom version are you using?
Block decorations were introduced in Atom v1.6.0.

**Comment by slavaGanzin** [comment]
@n-riesco Accidentally 1.4, but my package system was quite sure that 1.6. Thanks for that point

**Comment by n-riesco** [comment]
@slavaGanzin Note also that Atom v1.6.0 broke embedding images (see #204 ).

**Comment by slavaGanzin** [comment]
@n-riesco Already noticed :+1:

**Pull request merged**
