### PR TITLE
Greenkeeper/flow bin 0.54.0

### LINKED ISSUE #968: An in-range update of @nteract/transform-plotly is breaking the build 🚨
## Version **2.2.0** of [@nteract/transform-plotly](https://www.npmjs.com/package/@nteract/transform-plotly) just got published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="/nteract/hydrogen/compare/greenkeeper%2F%40nteract%2Ftransform-plotly-2.2.0">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </td>
    <td>
      @nteract/transform-plotly
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      2.1.1
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      dependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@nteract/transform-plotly is a direct dependency of this project **this is very likely breaking your project right now**. If other packages depend on you it’s very likely also breaking them.
I recommend you give this issue a very high priority. I’m sure you can resolve this :muscle:

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push** The Travis CI build failed [Details](https://travis-ci.org/nteract/hydrogen/builds/271278609?utm_source=github_status&utm_medium=notification)
</details>

---

<details>
<summary>Not sure how things should work exactly?</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html) and of course you may always [ask my humans](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### LINKED ISSUE #969: An in-range update of @nteract/transforms is breaking the build 🚨
## Version **2.4.0** of [@nteract/transforms](https://github.com/nteract/nteract) just got published.

<table>
  <tr>
    <th align=left>
      Branch
    </th>
    <td>
      <a href="/nteract/hydrogen/compare/greenkeeper%2F%40nteract%2Ftransforms-2.4.0">Build failing 🚨</a>
    </td>
  </tr>
  <tr>
    <th align=left>
      Dependency
    </td>
    <td>
      @nteract/transforms
    </td>
  </tr>
  <tr>
    <th align=left>
      Current Version
    </td>
    <td>
      2.3.0
    </td>
  </tr>
  <tr>
    <th align=left>
      Type
    </td>
    <td>
      dependency
    </td>
  </tr>
</table>

This version is **covered** by your **current version range** and after updating it in your project **the build failed**.

@nteract/transforms is a direct dependency of this project **this is very likely breaking your project right now**. If other packages depend on you it’s very likely also breaking them.
I recommend you give this issue a very high priority. I’m sure you can resolve this :muscle:

<details>
<summary>Status Details</summary>

- ❌ **continuous-integration/travis-ci/push** The Travis CI build failed [Details](https://travis-ci.org/nteract/hydrogen/builds/271278617?utm_source=github_status&utm_medium=notification)
</details>

---

<details>
<summary>Not sure how things should work exactly?</summary>

There is a collection of [frequently asked questions](https://greenkeeper.io/faq.html) and of course you may always [ask my humans](https://github.com/greenkeeperio/greenkeeper/issues/new).
</details>

---

Your [Greenkeeper](https://greenkeeper.io) Bot :palm_tree:

### PR DESCRIPTION
**Pull request by lgeiger**
**TODO:**
- [x] Update `@nteract/*` packages 🔜 https://github.com/nteract/nteract/pull/1871

Closes #968
Closes #969
Closes #968

### CODE REVIEW

**Comment by rgbkrk** [comment]
I'll ship a release of the nteract packages so you can carry on with this PR. 😄

**Comment by rgbkrk** [comment]
:ship: ed!

**Comment by lgeiger** [comment]
We haven't shipped a release for some time now. I think after this PR we can 🚢

**Comment by rgbkrk** [comment]
Oh man, this means that Hydrogen will have the new VDOM support before nteract desktop!

**Comment by lgeiger** [comment]
> Oh man, this means that Hydrogen will have the new VDOM support before nteract desktop!

Not yet. Hydrogen doesn't use `@nteract/transforms-full` since not all the transforms work with Atoms CSP.

**Comment by rgbkrk** [comment]
I... put it into `@nteract/transforms` as a default transform since `React` is effectively built in.

**Comment by lgeiger** [comment]
> I... put it into @nteract/transforms as a default transform since React is effectively built in.

Awesome didn't know that 🎉

**Pull request merged**
