### PR TITLE
Save kernelMapping on change

### LINKED ISSUE #271: grammarToKernel cut
I write grammarToKernel mapper that automatically saved on kernel change.

And now it doesn't work and I can't find it in repo:
https://github.com/nteract/hydrogen/search?utf8=%E2%9C%93&q=grammarToKernel

While @n-riesco recommend to use it:
https://github.com/nteract/hydrogen/issues/253

And it's present in Readme:
```
Additionally, if you have two or more kernels for a particular language (grammar), you can select which kernel to use with the "Switch to <kernel>" option in the Kernel Commands menu. This change is automatically saved into the Hydrogen configuration's ```grammarToKernel``` map. For example, if Hydrogen is using the kernel for Python 2 by default, you could switch to Python 3. Then next time you open a `.py` file, Hydrogen will remember your selection and use Python 3.
```

So if someone just cut this functionality, please document this fact.

p.s. I liked when I don't need to write mappings from babel kernel to jsx grammar, so why that was cutted?

### PR DESCRIPTION
**Pull request by slavaGanzin**
fixes #271

### CODE REVIEW

**Comment by n-riesco** [comment]
Kudos to @lgeiger (your tests have just caught a broken PR!)

**Comment by n-riesco** [comment]
@slavaGanzin are you trying to address #271 or #272 ?

**Comment by slavaGanzin** [comment]
#271. I'll reimplement/fix #272 in a while.

**Comment by n-riesco** [comment]
@slavaGanzin Please, don't commit changes to `master` without giving everyone a chance to review your changes!

f273e1d0e88bd4e1643318a9f3e27cdb66f7050f

**Comment by n-riesco** [comment]
Here's a list of the problems I've found so far:
- f273e1d allows the user to select any kernel, regardless of the file language.
- #270 has a number of issues, the most relevant to this PR is that the command `hydrogen:show-kernel-commands` should've been removed.

**Comment by slavaGanzin** [comment]
Definitelly, it do so. Because I fucked up with all javascript grammars I have in my setup, so I just want to match kernel to grammar. Editing JSON is not user "unfrendly", it's just a mess. I think it should update languageMappings too

Anyone could just switch to proper kernel. And not creating issues like that: https://github.com/nteract/hydrogen/issues/283#issuecomment-223997205

 And for example I work with jade(pug). It has inline jstransformers http://jade-lang.com/reference/filters/ and I want to switch between languages for one grammar.

>#270 has a number of issues, the most relevant to this PR is that the command hydrogen:show-kernel-commands should've been removed.
Let's vote @willwhitney @n-riesco @rgbkrk @lgeiger :
1. We should remove hydrogen:show-kernel-commands command - all commands of which now available in command pallete
2. 1 + remove dialog for kernels commands(that shown after click on kernel status in status line)
3. Leave everything as is

**Comment by slavaGanzin** [comment]
https://github.com/nteract/hydrogen/pull/284#issuecomment-224275289 My fault

**Comment by n-riesco** [comment]
I don't fully understand your post.


On 07/06/16 15:13, Slava wrote:
> Definitelly, it do so.

What do you mean by 'it'?

> Because I fucked up with all javascript grammars I have in my setup, so I just want to match kernel to grammar. Editing JSON is not user "unfrendly", it's just a mess. I think it should update languageMappings too

Do you mean to add a command to select a language mapping? I think that's a good idea.

> Anyone could just switch to proper kernel. And not creating issues like that: #283 (comment) <https://github.com/nteract/hydrogen/issues/283#issuecomment-223997205>

Issue #283 is totally unrelated and something hopefully I will address soon with a kernel launcher.

> [...]
> 
>     Let's vote @willwhitney <https://github.com/willwhitney> @n-riesco <https://github.com/n-riesco> @rgbkrk <https://github.com/rgbkrk> @lgeiger <https://github.com/lgeiger> :
>     1. We should remove hydrogen:show-kernel-commands command - all commands of which now available in command pallete
>     2. 1 + remove dialog for kernels commands(that shown after click on kernel status in status line)
>     3. Leave everything as is

Why the vote? Do you disagree with removing the command `hydrogen:show-kernel-commands`?

**Comment by slavaGanzin** [comment]
> f273e1d allows the user to select any kernel, regardless of the file language.
 Definitelly, it do so.

> Do you mean to add a command to select a language mapping? I think that's a good idea.
I think it would be good to omit using such mappings and merge it's functionality with kernelMappings. I mean map grammar to kernel directly. So i can run babel with jsx on jsx grammar and ijavascript without on regular js. Currently it can't be done - both babel/ijavascript are 'javascript' in kernelMappings sense.

> Why the vote?
I think cutting functionality should be done after voting. If we choose 2nd decision we can cut nearly 300 LOC and I'm not an author to be ultimate. 
I was surprised when saving of kernelMapping was cut, without voting. And now I redo it again because nobody voted against.

**Comment by n-riesco** [comment]
On 07/06/16 20:51, Slava wrote:
>     f273e1d <https://github.com/nteract/hydrogen/commit/f273e1d0e88bd4e1643318a9f3e27cdb66f7050f> allows the user to select any kernel, regardless of the file language.
>     Definitelly, it do so.

In other words, the functionality in f273e1d has been introduced on purpose.

>     Do you mean to add a command to select a language mapping? I think that's a good idea.
>     I think it would be good to omit using such mappings and merge it's functionality with kernelMappings. I mean map grammar to kernel directly. So i can run babel with jsx on jsx grammar and ijavascript without on regular js. Currently it can't be done - both babel/ijavascript are 'javascript' in kernelMappings sense.

Please, be respectful, revert f273e1d and open another issue to discuss this change.

>     Why the vote?
>     I think cutting functionality should be done after voting. If we choose 2nd decision we can cut nearly 300 LOC and I'm not an author to be ultimate.
>     I was surprised when saving of kernelMapping was cut, without voting. And now I redo it again because nobody voted against.

For the record, what you saw as feature to my eyes was a bug.

Issue #271 was open to discuss saving kernelMapping.
I said I didn't feel strongly about either option, but I prefer option 2.
@willwhitney said he didn't feel strongly about either option, but he prefers option 1.
You said you prefer option 1 and went ahead with this PR.

This PR saves the kernelMapping on `hydrogen:select-kernel`, but forgets to do the same on `hydrogen:show-kernel-commands`.

The ultimate reason why this happened is because your PR #270 duplicates the functionality provided by `SignalListView`. This doubles the amount of maintenance work we have to do (this PR being the first example).

I still don't see the need for a vote:

- removing the command `hydrogen:show-kernel-commands` doesn't remove functionality (this functionality is now provided by `hydrogen:select-kernel`)

- there is no need to remove the kernel functionality in the status line either.

**Comment by slavaGanzin** [comment]
> For the record, what you saw as feature to my eyes was a bug.
And so you decide to "fix" it without discussing with author. Great! 

I don't care about that command, but someone might.

**Comment by slavaGanzin** [comment]
https://github.com/nteract/hydrogen/pull/286

**Comment by n-riesco** [comment]
On 07/06/16 22:19, Slava wrote:
>     For the record, what you saw as feature to my eyes was a bug.

During the review of PR #177 I said that I didn't want the kernelSpec to be overwritten.
I even wrote the code for this not to happen. See here:

https://github.com/nteract/hydrogen/issues/173#issuecomment-188479594

Despite all that, PR #177 overwrites the kernelSpec (to my eyes, this is a bug)

As you see, this is not the first time we have tried to have a discussion, and my arguments go unanswered. I don't know the reason:
- is it because you didn't understand what I meant? (please, ask if anything I say isn't clear, don't just ignore it)
- if not, what was the reason?

The sad result is that Hydrogen doesn't work out of the box in Ubuntu (or anaconda, as #283 proves).


>     And so you decide to "fix" it without discussing with author. Great!

Seriously? Shall I apologise for fixing a bug in your code?

You know what is the saddest thing about this discussion?
That one-line edit would be enough to merge the output of `jupyter kernelspec` with the Hydrogen config.

**Comment by slavaGanzin** [comment]
> That one-line edit would be enough to merge the output of `jupyter kernelspec` with the Hydrogen config.

That is desired behavior, as I said before: https://github.com/nteract/hydrogen/issues/272#issuecomment-220797461

> *without discussing with author*
> Seriously? Shall I apologise for fixing a bug in your code?

Seriously. You can always create an issue and ask: is that's a bug or a feature? Can we improve that behavior?

p.s. I don't know why we always write that "poems". My English is bad, so I often mislead my reader.

**Comment by n-riesco** [comment]
On 08/06/16 00:20, Slava wrote:
>     That one-line edit would be enough to merge the output of |jupyter kernelspec| with the Hydrogen config.
> 
> That is desired behavior, as I said before: #272 (comment) <https://github.com/nteract/hydrogen/issues/272#issuecomment-220797461>

That is *your* desired behaviour! Why ignore that I have expressed that this is an undesirable behaviour?


>     /without discussing with author/
>     Seriously? Shall I apologise for fixing a bug in your code?
> 
> Seriously. You can always create an issue and ask: is that's a bug or a feature? Can we improve that behavior?

You mean to open another issue to discuss it again?
We had the discussion already in #173 and #177 and my comments were ignored.
I could only assume my comments weren't understood (because I didn't want to assume they had willingly been ignored).

> p.s. I don't know why we always write that "poems". My English is bad, so I often mislead my reader.

It's important that in an open forum like this all discussions are kept respectful.

**Comment by willwhitney** [comment]
Hey guys — 

Let's step back for a minute. 

We are all working toward the same goals. Everyone who is here is volunteering their time and energy. We will try to learn from one another's opinions, and we will make decisions by consensus, not by who committed last. 

From my understanding, this PR was originally intended to address #271 and persist selected kernels into the config mapping. If there are no objections to this change, please make this PR contain only that and nothing more.

If the point in question is #272, let's move the discussion there. (If not, please point me in the right direction.)

**Comment by n-riesco** [comment]
@willwhitney I'm afraid the situation is more complicated than that:

- @slavaGanzin committed https://github.com/nteract/hydrogen/commit/f273e1d0e88bd4e1643318a9f3e27cdb66f7050f directly to master (despite [having been advised in the past](https://github.com/nteract/hydrogen/commit/80874a9a2141e5f506ae1d28c678e10edc31c8f1#commitcomment-16251670) not to do so).

- this PR is built on top of https://github.com/nteract/hydrogen/commit/f273e1d0e88bd4e1643318a9f3e27cdb66f7050f

- this PR fails to update `kernelMappings` when the functionality in `SignalListView` is used.

The way I see this situation is:
1. https://github.com/nteract/hydrogen/commit/f273e1d0e88bd4e1643318a9f3e27cdb66f7050f should be reverted immediately
2. this PR should be updated so that `SignalListView` also saves `kernelMappings`

**Comment by slavaGanzin** [comment]
> That is *your* desired behaviour! Why ignore that I have expressed that this is an undesirable behaviour?

Why? Why merging kernelMapping from jupyter output and your specified setting is undesired behavior?

p.s. I had revert f273e1d from master yesterday, the same commit comes to this PR, because at a time of creation I based on master with that commit.

**Comment by n-riesco** [comment]
On 08/06/16 10:00, Slava wrote:
>     That is /your/ desired behaviour! Why ignore that I have expressed that this is an undesirable behaviour?
> 
> Why? Why merging kernelMapping from jupyter output and your specified setting is undesired behavior?

The undesirable behaviour was that Hydrogen before #260 overwrote the kernelSpec manually set by the user.

> p.s. I had revert f273e1d <https://github.com/nteract/hydrogen/commit/f273e1d0e88bd4e1643318a9f3e27cdb66f7050f> from master yesterday, the same commit comes to this PR, because at a time of creation I based on master with that commit.

I've tested the updated PR and now works as expected. +1 for merging.

**Comment by slavaGanzin** [comment]
@n-riesco If we merge settings and jupyter/ipython and I think https://github.com/nteract/kernelspecs would it be ok to your use cases?

**Comment by n-riesco** [comment]
@slavaGanzin For the time being, I think it'd be enough to replace

https://github.com/nteract/hydrogen/blob/e52911d9ca51a21eb7c7b864175f27bac5b40d5e/lib/kernel-manager.coffee#L46

with

```
Config.setJson 'kernelspec', kernelspecs: newKernelSpecs, true
```

**Comment by slavaGanzin** [comment]
1. It will create a mess with user defined kernelMappings
2. If user delete a kernel it would be present in kernelMappings

**Comment by n-riesco** [comment]
On 08/06/16 13:14, Slava wrote:
>  1. It will create a mess with user defined kernelMappings
>  2. If user delete a kernel it would be present in kernelMappings

`kernelMappings` and `kernelSpecs` are different settings.

**Comment by slavaGanzin** [comment]
Ok. KernelSpecs

**Comment by willwhitney** [comment]
As the project has grown it is very important to make changes in PRs, even though it's a little more running around. PRs let people see what's going on and comment on it much more easily than direct commits. Thank you for correspondingly reverting that commit, @slavaGanzin.

I believe the `_.assign` call ([L44](https://github.com/nteract/hydrogen/blob/e52911d9ca51a21eb7c7b864175f27bac5b40d5e/lib/kernel-manager.coffee#L44)) means this code is the same as setJson with `merge=true`, at least if `parseKernelSpecSettings` doesn't reject any kernelspecs. Or am I misreading?

**Comment by n-riesco** [comment]
@willwhitney you're right. I misremembered. `saveKernelSpecs` already merges any updates to `kernelSpec`.

@slavaGanzin isn't it working for you?

**Comment by slavaGanzin** [comment]
This PR is about kernelMappings. 

But I think newKernelSpecs shouldn't be saved into kernelSpecs. Because when you will sync your settings to another machine you'll see "ghost" kernels. Is this clear?

**Comment by willwhitney** [comment]
So the flow I'm seeing right now is that on activation, Hydrogen saves the kernelspecs it gets from `jupyter kernelspec list --json` or `ipython kernelspec list --json` into the Atom config.

I assume we're doing this so that users have a back door to fix things? My first instinct is that it's better to rely purely on those calls and not have extra Hydrogen-specific configuration around this, but if there was good rationale at the time that's fine.

@slavaGanzin If we're keeping track of kernels this way, I'm not sure what to tell you, other than "don't sync files that contain system-specific information".

Another solution would be to make the config field exclusive to user-specified kernelspecs. That way the system kernelspecs (the ones found by `jupyter kernelspec`) will be loaded per-machine and not saved.

**Comment by lgeiger** [comment]
This PR looks good to me 👍 

> Another solution would be to make the config field exclusive to user-specified kernelspecs. That way the system kernelspecs (the ones found by jupyter kernelspec) will be loaded per-machine and not saved.

I would like to go a step further. We could remove the kernelspecs setting and give the user the option to define paths to additional `kernel.json` files. So you could connect to additional kernels even if they are not present in the default jupyter directory (#287).

**Comment by slavaGanzin** [comment]
#287 
I think it's really great idea to add parsing  ``` .atom/hydrogen/kernels/*.json ``` and remove kernelMapping from config.

**Comment by n-riesco** [comment]
On 09/06/16 18:57, Will Whitney wrote:
> I assume we're doing this so that users have a back door to fix things? My first instinct is that it's better to rely purely on those calls and not have extra Hydrogen-specific configuration around this, but if there was good rationale at the time that's fine.

The rationale is that there are cases where Atom is unable to run the commands `ipython kernelspec list` and `jupyter kernelspec list`; e.g.:
- Ubuntu 16.04 LTS
- Anaconda
 
> @slavaGanzin <https://github.com/slavaGanzin> If we're keeping track of kernels this way, I'm not sure what to tell you, other than "don't sync files that contain system-specific information".

The solution below (if I understood correctly) is what Slava suggested to fix his use of Hydrogen.

> Another solution would be to make the config field exclusive to user-specified kernelspecs. That way the system kernelspecs (the ones found by |jupyter kernelspec|) will be loaded per-machine and not saved.

+1

**Comment by n-riesco** [comment]
On 09/06/16 23:06, Lukas Geiger wrote:
> I would like to go a step further. We could remove the kernelspecs setting and give the user the option to define paths to additional |kernel.json| files. So you could connect to additional kernels even if they are not present in the default jupyter directory (#287 <https://github.com/nteract/hydrogen/issues/287>).

I like this idea better. It's more flexible.

**Comment by n-riesco** [comment]
About #287 , note that the `kernel-xxxx.json` files are connection files, not kernel specs. Having a setting to define additional paths to search kernel specs won't fix #287 (though, it will help towards fix it).

**Comment by n-riesco** [comment]
BTW, shouldn't we be having this discussion in #272 and merge #271 now?

**Comment by lgeiger** [comment]
> About #287 , note that the kernel-xxxx.json files are connection files, not kernel specs. Having a setting to define additional paths to search kernel specs won't fix #287 (though, it will help towards fix it).

Yes you are right. [This comment](https://github.com/nteract/hydrogen/issues/287#issuecomment-225040979) explains it great!

**Pull request merged**
