### PR TITLE
New watch expression demo image

### PR DESCRIPTION
**Pull request by lgeiger**

### CODE REVIEW

**Comment by rgbkrk** [comment]
:eyes: soooooo good

**Comment by rgbkrk** [comment]
Want me to make a patch release?

**Comment by lgeiger** [comment]
I had to try out my new gif tool :wink: 

:+1: for a patch release!

**Comment by rgbkrk** [comment]
Done!

**Comment by lgeiger** [comment]
Wuhu 15000+ Downloads! :tada: 
bildschirmfoto 2016-03-30 um 02 06 00

**Comment by rgbkrk** [comment]
I wish we had better insight into # of users or at least time series data on downloads - we get a lot of "downloads" just in upgrading. This is likely misleading for atom-script, which in the past upgraded fairly regularly:

screenshot 2016-03-29 19 38 46

**Pull request merged**
