### PR TITLE
Revert Accidental Change to Multi-Grammar Files

### LINKED ISSUE #1636: Markdown cells return wrong result
Inside an .md file with the following code (replace brackets with 3 `):
```
{python
#%%md
print('hi')
}
```
The runCell() result includes the cell header and it renders in between line 2 and 3.

Related Issue:
Inside an .md file with the following code (replace brackets with 3 `):
```
#%%md
{python
print('hi')
}
```
The runCell() result returns a markdown result and not a code result

### PR DESCRIPTION
**Pull request by wadethestealth**
## Reason
When implementing #1628 I accidentally edited functionality I was unaware wasn't supposed to be possible.
This reverts those changes.

## Notes
- When you merge this **do not** merge the first commit of this PR.
- Closes #1636

### CODE REVIEW

**Comment by aviatesk** [comment]
> When you merge this do not merge the first commit of this PR.

Do you mean you want to rebase the commit ?

**Comment by wadethestealth** [comment]
That is fine. I didn't know how to delete it and didn't want to Google it at the time, but just the second commit is the one needed

**Comment by aviatesk** [comment]
@wadethestealth Okay. Let's keep the history.

Anyway, I think the change like I committed just now is still needed for fended code cells to work well.
Without the change, a result would be like:
image

**Comment by wadethestealth** [comment]
> Anyway, I think the change like I committed just now is still needed for fended code cells to work well.

You are correct. I had forgotten why I made that change thank you. @aviatesk

**Pull request merged**
