### PR TITLE
Convert to TypeScript

### PR DESCRIPTION
**Pull request by aminya**
This converts the codebase to TypeScript

Requires:
https://github.com/nteract/kernelspecs/pull/35
https://github.com/nteract/jupyter-paths/pull/39

### The tests

The tests are all passing
https://github.com/aminya/hydrogen/actions/runs/733861352

### How to test the functionality
```
git clone https://github.com/aminya/hydrogen.git
cd hydrogen
git checkout typescript
apm install
npm run build
apm link .
atom .
```
Make sure to run `apm unlink .` after you're done testing, so you don't miss the official versions.

### How to review
You can go through the commits which include the mental logic behind the changes.

The first [commit conversion](https://github.com/nteract/hydrogen/pull/2063/commits/aed4482c9045aeec5de20abe2ce1ccaf6b31ab2a) is done automatically using [@khanacademy/flow-to-ts](https://github.com/Khan/flow-to-ts), and then the issues are fixed by hand. 

If you want to verify the changes make sure to disable the whitespace changes generated by the tool.

### CODE REVIEW

**Review by aminya — COMMENTED** [review]
I am about to merge this if no one has any concerns. It would be nice if someone could test the functionality under a different workflow.

**Comment by n-riesco** [comment]
@aminya I've been keeping an eye on this PR, so I could give you some comments (but not this weekend).

PS: I haven't kept up to date with nteract's libraries. I won't be able to give you feedback on their use.

**Comment by aminya** [comment]
Thanks. If you can just build and use this a bit, it would be enough.

**Comment by aminya** [comment]
I am going to merge this for now as I want to make some other changes. You can test the functionality on master.

**Pull request merged**
