### PR TITLE
ZMQKernel: Unmonitor sockets after connection

### LINKED ISSUE #646: constant 10% CPU by Atom Helper after python kernel is launched on Mac OS
**Description:**

constant 10% cpu by Atom Helper. Attaching the profile sample of running process.  

**Steps to Reproduce:**
Open python code. Launch python kernel. 

**Versions:**

Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Hydrogen: 1.6.0

**Logs:**
[Sample of Atom Helper.txt](https://github.com/nteract/hydrogen/files/853719/Sample.of.Atom.Helper.txt)

Please post any error logs and the output of the developer tools as described in our [Debugging Guide](https://github.com/nteract/hydrogen/blob/master/TROUBLESHOOTING.md).

### PR DESCRIPTION
**Pull request by n-riesco**
Fixes #646

### CODE REVIEW

**Comment by n-riesco** [comment]
@lgeiger @BenRussert I don't think it will, but could you check if this PR has any effect on #591? (Please, reinstall IJavascript so that it picks up the latest version of jp-kernel)

**Comment by n-riesco** [comment]
I'll address the flow failure after I know if this PR fixes #591 too.
If it does, I can get rid of the callback in `_connect`.

**Comment by BenRussert** [comment]
[Seems about the same to me](https://www.youtube.com/watch?v=XVc9G19OpLY)

**Comment by lgeiger** [comment]
This doesn't fix #591 for me.

I'm personally in favor of completely removing the monitoring. Are you sure that #88 is still a issue with our current version of zeromq?

**Comment by n-riesco** [comment]
@BenRussert Could you post the output of running `ijsinstall --versions`? I want to make sure your installation is using `jp-kernel@0.1.2`.

@lgeiger Does it fix #646?

> I'm personally in favor of completely removing the monitoring. Are you sure that #88 is still a issue with our current version of zeromq?

The only workaround I know to fix #591 involves using `socket.monitor`. Are you suggesting to close #591 as `wontfix`?

**Comment by n-riesco** [comment]
I've updated this PR to implement [this workaround](https://github.com/n-riesco/ijavascript/pull/103/commits/0824d1e168551c9c5b3bb59d5b3f39532a2c776e) in Hydrogen. I haven't implemented the [second workaround](https://github.com/n-riesco/ijavascript/pull/103/commits/9c2cf6a94575b5016b4a6f3cbe380ab1fcfbcf76), because I don't expect Hydrogen to send messages fast enough to trigger the issue in zeromq.

@BenRussert @lgeiger Please, could you make sure IJavascript is using jp-kernel@0.1.2 and test if this PR fixes #591?

**Comment by n-riesco** [comment]
@BenRussert Thank you for the video. The logs in the video made me realise I hadn't removed the old connect handlers.

**Comment by BenRussert** [comment]
@n-riesco I did not update ijavascript before this, so if it's a new release (~two weeks) I most likely did not use it in the video. Will try that when I get home and see if I get the same results as @lgeiger

**Comment by BenRussert** [comment]
This fixes #591 for me! The only weird part is `ijsinstall --versions` shows that I am not on jp-kernel 0.1.2:

```
ijavascript 5.0.19
jmp 0.7.5
jp-kernel 0.1.1
nel 0.5.1
uuid 3.0.1
zeromq 4.2.0
```

> @BenRussert can you still reproduce it?
Yes, I just did on master after confirming @n-riesco's branch fixes the issue. I can reproduce on master, but checking back out `unmonitor` fixes it.

**Comment by lgeiger** [comment]
> The only weird part is ijsinstall --versions shows that I am not on jp-kernel 0.1.2:

I think running `npm uninstall ijavascript -g` and `npm i ijavascript -g` should make sure that you have the newest version.

Could you test if it works on master, after upgrading?

**Comment by n-riesco** [comment]
@BenRussert Thanks for testing.

The main change between `jp-kernel@0.1.1` and `jp-kernel@0.1.2` is that 0.1.1 uses `socket.bind`, whereas 0.1.2 uses `socket.bindSync`. This means that now the IJavascript kernel either succeeds to bind to the connection sockets or dies (before it'd try to continue silently).

**Comment by BenRussert** [comment]
> I think running npm uninstall ijavascript -g and npm i ijavascript -g should make sure that you have the newest version.

This worked to update jp-kernel, thanks! Shouldnt `npm upgrade ijavascript -g` work as well? It didnt seem to.

> Could you test if it works on master, after upgrading?

master still has same issue #591.

**Comment by lgeiger** [comment]
> master still has same issue #591.

Hmm, I hoped the new version would fix it on other machines as well.

I wonder if it's enough to wait for the `connect` event don't monitor at all?

**Comment by n-riesco** [comment]
> Hmm, I hoped the new version would fix it on other machines as well.

@lgeiger I don't think that's what Ben means.

Please, @BenRussert correct me if I'm wrong:
- from [this comment](https://github.com/nteract/hydrogen/pull/678#issuecomment-290566157) I understand this PR fixes #591
- and from [this comment](https://github.com/nteract/hydrogen/pull/678#issuecomment-290676822)  I understand that Hydrogen without this PR still suffers from #591 (i.e. jp-kernel@0.1.2 has no effect; this PR is the actual fix for #591).

**Comment by BenRussert** [comment]
@n-riesco has my results correct above:
This PR (branch `unmonitor` ) fixes the issue for me.

**Comment by rgbkrk** [comment]
I'm leaning towards going ahead with merging this based on feedback from @BenRussert and @n-riesco, then people can keep iterating and simplifying right after.

**Comment by BenRussert** [comment]
What is the appropriate emoji when a bug is squashed? Best attempt 🐛 👏 or 🐛 🚽

**Comment by lgeiger** [comment]
👍 Let's go with this. @n-riesco Thanks a lot for all the work!

I was a bit sceptical since this does impact startup speed of the standard python kernel (approx x2) but it's still reasonably fast 🚀

**Comment by lgeiger** [comment]
> What is the appropriate emoji when a bug is squashed? 

@BenRussert My best attempt 😆 :🚫 🐛 or 🔥 🐛

**Comment by BenRussert** [comment]
> this does impact startup speed of the standard python kernel (approx x2)

I didn't check for this. New issue worthy?

Overall this closes two of the most wanted issues in my opinion, I agree with the props to @n-riesco!

**Comment by lgeiger** [comment]
> New issue worthy?

If you like you can make a new issue to remind us to revisit this workaround, once the root problem is fixed in ijavascript and zeromq.js.

In any case we should make a new release soon :shipit:

**Pull request merged**
