### PR TITLE
Style Block decorations 

### PR DESCRIPTION
**Pull request by lgeiger**
I started playing around with the block decorations. The next few days I will work a lot with hydrogen so I can test this PR and probably I will find some more styling problems. What do you think about the styling so far?
New:
pr
Master:
master

### CODE REVIEW

**Comment by n-riesco** [comment]
I like the shadow in the multiline bubbles. Could we have them as well in the in the single line bubbles too?

**Comment by lgeiger** [comment]
bildschirmfoto 2016-03-21 um 00 20 31

**Comment by rgbkrk** [comment]
Think this is fit to ship now?

**Comment by n-riesco** [comment]
How does it work? Is it the `float:left` what makes the block decoration to be on the same line?

**Comment by lgeiger** [comment]
@rgbkrk There are just some minor inconsistencies but nothing major. If you like you can merge and I fix these in a future PR.

@n-riesco It's the negative [`margin-top`](https://github.com/nteract/hydrogen/pull/213/files#diff-2e1bb36917ff76ab7308da52bc968501R163) in combination with `float: left`. I just played around with the values until it worked ;).

**Comment by n-riesco** [comment]
Neat!

**Comment by rgbkrk** [comment]
We fit to take this in now @n-riesco?

**Comment by lgeiger** [comment]
I just noticed a little problem with the watches panel. It'll be ready in a few minutes ;)

**Comment by rgbkrk** [comment]
Ah, sorry. I noticed the `[WIP]` tag coming off and assumed that was you stating intent. :smile:

**Comment by lgeiger** [comment]
I'm  good with merging it!

You are right. At the time I removed the `[WIP]` I thought it was ready. :laughing:

**Comment by n-riesco** [comment]
@lgeiger Check the SVG example you gave me.

I gotta go offline for a while.

**Comment by lgeiger** [comment]
@n-riesco The SVG output looks good to me.

**Comment by n-riesco** [comment]
@lgeiger I've tested this branch and works well in my machine.

PS: The problem I saw before was actually caused by the beta version of the IJavascript kernel.

**Comment by lgeiger** [comment]
@n-riesco no problem. Thanks for the testing.

**Comment by rgbkrk** [comment]
Anything else we want to do before we make a release?

Were people willing to try out `zmq-prebuilt`? It has prebuilds for Linux, OS X, and 32-bit Windows. 64-bit Windows users still have to build (as they would in the past too).

**Comment by n-riesco** [comment]
@rgbkrk This is now just a question of replacing the `jmp` dependency with `jmp-prebuilt`.

**Pull request merged**
