### PR TITLE
Fix issue #76 (bubble removed after enter)

### LINKED ISSUE #76: Output disappears when hitting enter/return/newline
It seems that in general Hydrogen will keep output in place when you modify the line that you've just evaluated. For example,

```python
foo(3)  #output here
```
if you edit this to say `foo(2)` after evaluating it, the "#output here" will stay in place. You can even insert many more characters and the output will flow along to the right. But if you hit enter to go to the next line, it disappears. I try to remember to hit enter *before* evaluating, but it's difficult.

This would help screencasting go better :)

### PR DESCRIPTION
**Pull request by n-riesco**
Fixes #76

### CODE REVIEW

**Comment by willwhitney** [comment]
This looks pretty good to me. Since these are flow-breaking changes for the user, I'll wait to do a more thorough review and merge this when I release other major changes.

**Comment by n-riesco** [comment]
Would you want me to split the PR?
4cef6d6 is actually a bug fix.

**Comment by willwhitney** [comment]
Ah, that’d be great!

**Comment by n-riesco** [comment]
#102

**Comment by willwhitney** [comment]
@n-riesco is this ready to go? We split out the bug fix and I think that got merged, so is this mergeable?

(Sorry for the embarrassing delay — lost track of this PR)

**Comment by n-riesco** [comment]
Is it alright if I look at this in January? I'm currently travelling.

**Comment by willwhitney** [comment]
Yup, no worries. I'm obviously not one to talk :)

**Comment by rgbkrk** [comment]
Since you did #102 @n-riesco, should we close this down or would you want to make more progress?

**Comment by rgbkrk** [comment]
I'm going to post an issue about where I'd like to take a refactor here as well as start thinking about/experimenting with the new inline support in Atom.

**Comment by n-riesco** [comment]
I'm really sorry. I completely forgot about this PR.

This PR is really about whether we want two bindings to execute code:
```
'cmd-alt-enter': 'hydrogen:run-and-move-down'
'shift-alt-enter': 'hydrogen:run'
```

I'd like to hear what others think? Is this worth having? Are choice of bindings OK?

**Comment by rgbkrk** [comment]
I agree with us having two bindings for executing code. The notebook has this notion too. 
`ctrl-enter` tends to mean "just run" while `shift-enter` means "run and move down". I'm guessing these conflicted with other Atom bindings at the time of creation (or an unwillingness to cover a binding used elsewhere), so we may not match amongst bindings with the notebook environments.

**Comment by willwhitney** [comment]
Yep, when I first wrote this `shift-enter` was bound to something else by default in Atom. Not sure if it still is.

**Comment by n-riesco** [comment]
Shall we merge this PR as it is?

**Comment by rgbkrk** [comment]
Yeah, let's go for it and iterate.

**Pull request merged**
