### PR TITLE
tweak autocompletion style

### PR DESCRIPTION
**Pull request by aviatesk**
- #1727 can show silly large description, and this PR suppress that more

### CODE REVIEW

**Comment by wadethestealth** [comment]
Does this add scroll bar or use an elipse? Can I get a screenshot example?

**Comment by aviatesk** [comment]
> Does this add scroll bar or use an elipse?
No, would be better if we could tho

**Comment by wadethestealth** [comment]
Can I see what it looks like and I think both options are fine.

**Comment by aviatesk** [comment]
Ah sorry, I found that the other package (atom-ink) had a change like:
```
autocomplete-suggestion-list.select-list.popover-list {
    .suggestion-description {
      line-height: 1;
      .suggestion-description-content {
        overflow-y : hidden;
        display    : inline;
        white-space: normal; // can be useful to workaround https://github.com/atom/autocomplete-plus/issues/868
      }
    }
  }
```

and actually `display    : inline;` made something like:
image

But it's now fixed with: https://github.com/JunoLab/atom-ink/pull/217
and there is no more annoyance, so gonna close this.

Sorry for taking your time !

**Pull request closed without merging**
